# ======================================
# CATALOG SERVICE - Application Config
# ======================================

# Server
server.port=8081
spring.application.name=catalog-service

# MySQL Database
spring.datasource.url=jdbc:mysql://localhost:3306/catalog_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=system
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialec #changing this dialact because after spring-cloud-version changed to 2025.0.1(for using FeignClient, Eureka discovery etc all comes under spring-clound),Spring Boot 3.5.x uses Hibernate 6.6+ under the hood. Hibernate 6 has completely dropped support for the generic org.hibernate.dialect.MySQLDialect class. 
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true

# Logging
logging.level.com.ott.catalog=DEBUG
logging.level.org.springframework.web=INFO

# ── Spring Boot Actuator + Prometheus Monitoring ──────────────────
#
# management.endpoints.web.exposure.include
# Controls which /actuator/* endpoints are publicly accessible
# prometheus = required for Prometheus to scrape metrics
# health     = required for AWS load balancer health checks
# info       = shows app version and description
# metrics    = shows list of all available metrics
#
# management.endpoint.health.show-details=always
# Shows DB status, disk space, Redis status in health response
#
# management.metrics.tags.application
# Adds app name label to every metric — so Grafana can distinguish
# which service the metric came from (catalog vs subscription vs gateway)

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.metrics.tags.application=catalog-service
management.info.env.enabled=true

# App info shown at /actuator/info
info.app.name=Catalog Service
info.app.version=1.0.0
info.app.description=OTT Platform - Manages OTT subscription plans